services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: node_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
    command: bash -c "npm install && npm start"

  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: etterem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
